### ISSUE TITLE
docker setup problem 

### ISSUE THREAD

**Issue by jianbosu** [docker-library/docs#1157]
i can running redmine direct from docker-compose up.but i want to run with myql that out of container.i wroten a yml file linke this ：
version: '3.1'

services:

  redmine:
    image: redmine
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: ip address
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmineps
    volumes:
      - app_data:/usr/src/redmine/files
volumes:
  app_data:
---------------------------------------------------------------------------------
but when i run up,get error
---------------------------------------------------------------------------------
redmine_1  | The Gemfile's dependencies are satisfied
redmine_1  | rake aborted!
**redmine_1  | Mysql2::Error: Access denied for user 'redmine'@'171.92.207.173' (using password: YES)**
redmine_1  | /usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
redmine_1  | /usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
redmine_1  | /usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
redmine_1  | /usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
redmine_1  | /usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
redmine_1  | /usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'

how to fix the problem?

**Comment by tianon** [comment]
Your error message (`Access denied for user 'redmine'@'171.92.207.173' (using password: YES)`) leads me to believe this is a credentials issue -- does your remote MySQL instance have a `redmine` user?  Is it allowed to connect via `171.92.207.173`?  Is the password correctly configured?

Since this doesn't appear to be an issue with the image (or the docs), I'm going to close.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
