### ISSUE TITLE
[!!!!!!] Failed to mount API filesystems, freezing.

### ISSUE THREAD

**Issue by zach007** [docker-library/docs#1223]
what is this mean ?
[!!!!!!] Failed to mount API filesystems, freezing.
and it doesn't work about with systemed follow the documents.

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by tianon** [comment]
Closing, given that there's not enough information here to determine what the issue is -- additionally, this is definitely not the right place to file this issue.  This repository is for the image documentation.

I would suggest posting to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) for further help debugging your system.
