### ISSUE TITLE
Document how to use docker-library-bot

### ISSUE THREAD

**Issue by J0WI** [docker-library/docs#1248]
@docker-library-bot seems to update various "official" repos, but this feature is nowhere documented.
Would be great to get some info about that.

Edit: Here is an [example](https://github.com/matomo-org/docker/commit/edd76a3640e34e8318f7dbb08b4875838cb83e0c).

**Comment by tianon** [comment]
It's not really anything formal (calling it a "feature" is a bit of a stretch) -- it's a Jenkins user we set up to help us manage all the image repos under https://github.com/docker-library (all of which have an `update.sh` to bump version numbers and a `generate-stackbrew-library.sh` to generate the relevant `library/REPO` file contents).

See https://doi-janky.infosiftr.net/job/update.sh/ for the Jenkins jobs (which are linked from each image repo `README.md` file) and https://github.com/docker-library/oi-janky-groovy/tree/238af3cbad31c9a27cc9d450c951a68c46d408ba/update.sh for the Groovy scripts.  It works well enough for us that several other repos have asked to be included (which can be seen in `vars.groovy` in that linked repo).

IMO this doesn't really warrant any further documentation since it's not really a "feature" and is simply how we maintain things -- every image maintainer is welcome to do their own thing.

**Comment by J0WI** [comment]
I think [here](https://github.com/docker-library/docs#what-are-all-these-files) or [here](https://github.com/docker-library/official-images#table-of-contents) would be a great place to mention that.

**Comment by J0WI** [comment]
@tianon I tired to automate the Joomla image, but the `generate-stackbrew-library.sh` [is ignored by the bot](https://github.com/joomla/docker-joomla/issues/64#issuecomment-402695872).

**Comment by tianon** [comment]
Making PRs to https://github.com/docker-library/official-images isn't something the bot does (it only automates `./update.sh`, test building, and committing) -- that's something I do manually.

**Comment by wglambert** [comment]
Going to close as the question is answered sufficiently
