### ISSUE TITLE
Linked repositories seems vanished

### ISSUE THREAD

**Issue by waja** [docker-library/docs#1423]
https://github.com/docker-library/docs/blob/master/wordpress/README.md#adding-additional-libraries--extensions has a link to [Repository Links](https://docs.docker.com/docker-hub/builds/#repository-links), which is broken. It seems as linked repositories are not supported anymore with the "new" Docker Hub.

**Comment by tianon** [comment]
Yeah, I was wondering about this apparent removal myself the other day. :confused:

I'm not sure whether it's gone, or whether they simply trigger builds more intelligently based on `FROM` now, but the best we can do here is ping Docker folks (since we're not officially involved with the Hub team), and we've done so (but haven't heard back).  Sorry!

**Comment by tianon** [comment]
Doh, just realized you also noted we have dead links, sorry!  Opening a PR in just a sec to axe those (since there's nothing more we can do).

**Comment by waja** [comment]
> I'm not sure whether it's gone, or whether they simply trigger builds more intelligently based on `FROM` now, but the best we can do here is ping Docker folks (since we're not officially involved with the Hub team), and we've done so (but haven't heard back). Sorry!

I also contacted their support stuff but haven't heard back since now. Can you please update me on this when you have news on this please?
