### ISSUE TITLE
MongoSocketReadException: Prematurely reached end of stream

### ISSUE THREAD

**Issue by Tset-Noitamotua** [docker-library/docs#1444]
what I do
1. start docker container  MongoDB
2. wait until MongoDB fully started
3. start java spring boot application
4. interact with application
5. stop docker container    MongoDB
6. remove docker container    MongoDB
7. start docker container    MongoDB
8. wait until MongoDB fully started

what I get
```
Failed to call access method:
org.springframework.data.mongodb.UncategorizedMongoDbException:
Prematurely reached end of stream; nested exception is
com.mongodb.MongoSocketReadException: Prematurely reached end of stream
```

**Comment by wglambert** [comment]
This could be a configuration issue with either the [keep-alive timeout](https://stackoverflow.com/a/39369698) or an error with [connecting to mongo](https://stackoverflow.com/questions/48979191/com-mongodb-mongosocketreadexception-prematurely-reached-end-of-stream). If you find that it is an error with the way we package the mongo image then creating a minimal reproducer of the issue would allow us to probe around for what the error is.

Since this looks like an issue with your environment/config you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability

**Comment by Tset-Noitamotua** [comment]
Thanks for reply and provided references. I can workaround the issue by increasing the wait time between each step.
