### ISSUE TITLE
arm64v8 ubuntu14.04 ros-indigo docker

### ISSUE THREAD

**Issue by gakkiHp** [docker-library/docs#1447]
@yosifkit 
Hello, I have a problem. I can't find the docker based on arm64v8 ubuntu14.04+ros indigo, can you find it, I didn't see it on dockerhub

**Comment by wglambert** [comment]
https://hub.docker.com/r/arm64v8/ros/

**Comment by gakkiHp** [comment]
@wglambert 
Thanks a lot, but it seems that the link does not have indigo.

**Comment by wglambert** [comment]
Looks like they've moved tags/repos around https://github.com/osrf/docker_images/issues/232
I think this is what you want https://hub.docker.com/r/osrf/ros 
https://github.com/osrf/docker_images

I'm not familiar with their image/tagging structure so I'm kind of lost as to what to pull since the documentation doesn't seem to indicate what is what and where (can't pull `ros:indigo` but can pull `osrf/ros:indigo-desktop-full`). Since they're the maintainers I'd look through their issues about Dockerhub over at https://github.com/osrf/docker_images/issues?q=is%3Aissue+is%3Aclosed

**Comment by gakkiHp** [comment]
@wglambert 
Thank you very much for your suggestion. I found the relevant image in the link, but it seems that it is not based on arm64v8, so I get an error.

**Comment by wglambert** [comment]
Oh yeah I see what you mean, I was pullin `ros:indigo` on an arm server and was getting an error. On amd64 it's there.
The `indigo` tag isn't actually listed under arm64v8 https://hub.docker.com/r/arm64v8/ros/

Looking at our [library list](https://github.com/docker-library/official-images/blob/master/library/ros#L10-L28); only arm32v6 is supported for indigo on `ros`. For their other repos maybe they have other variations/support

**Comment by tianon** [comment]
Yep, https://github.com/osrf/docker_images/issues is the appropriate place to discuss `ros` supported architectures further.

**Comment by gakkiHp** [comment]
@wglambert @tianon 
So what you mean is that I may not be able to get the image I want？

**Comment by tianon** [comment]
You might be able to build one, but they don't officially publish one (and
this is the wrong place to ask about it).

**Comment by gakkiHp** [comment]
OK, thanks a lot, i have moved it to another place. https://github.com/osrf/docker_images/issues/237
