### ISSUE TITLE
docker run --link is deprecated

### ISSUE THREAD

**Issue by AkihiroSuda** [docker-library/docs#1536]
https://github.com/docker-library/docs/tree/44e1657a6d4c7ec1c4aa803d247d093a330d9cfc/docker 

The dind content.md suggests using `docker run --link`, but it has been deprecated: https://docs.docker.com/network/links/

**Comment by wglambert** [comment]
A lot of the `--link`'s were replaced in https://github.com/docker-library/docs/pull/1441

https://github.com/docker-library/faq#--link-is-deprecated

**Comment by tianon** [comment]
Indeed -- this one was left alone because it was still using the `DOCKER_PORT_2375_TCP` environment variable for detection, which is the reason why https://github.com/docker-library/docker/pull/166/files#diff-60713fb19f6c50a2473835df63ff17f9L15 included changes to always set `DOCKER_HOST` if it isn't set and `/var/run/docker.sock` doesn't exist (with the express goal of updating this documentation).

**Comment by tianon** [comment]
https://github.com/docker-library/docs/pull/1538 :+1:
