### ISSUE TITLE
Cannot access 8000 port through http/WS

### ISSUE THREAD

**Issue by xishengzhang** [docker-library/docs#1643]
Hello, I want to know why I cannot access the 8000 through http or websocket after running the container on docker? the command I used is "docker run --name some-kaazing-gateway -h somehostname -e GATEWAY_OPTS="-Dgateway.hostname=somehostname -Xmx512m -Djava.security.egd=file:/dev/urandom" -v /some/gateway-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro -d kaazing-gateway". Before running the command I have a mapping with my linux PC IP and somehostname under /etc/hosts file. 
Thanks a lot

**Comment by wglambert** [comment]
You'll want to publish that port with `-p 8000:8000` https://docs.docker.com/config/containers/container-networking/#published-ports

For further questions you should ask over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
