### ISSUE TITLE
Update status of slim variants

### ISSUE THREAD

**Issue by J0WI** [docker-library/docs#1645]
> These tags are an experiment [...] and are definitely subject to change.

https://github.com/docker-library/docs/blob/master/debian/variant-slim.md

Meanwhile they are widely used and pretty stable, aren't they?

**Comment by tianon** [comment]
They are widely used and have been pretty stable, but I think it still makes sense to include the experimental text due in part to the fact that "Debian Buster Slim" isn't a thing that exists -- we have a "Debian Buster" image which has a "slim" variant concocted by me and @paultag, and it doesn't represent an official "release artifact" of the Debian project at large, so that's the sense from which I still consider it "an experiment".

If someone doesn't know the low-level details of what it is and how it's made, I'm going to recommend they use the non-slim variants every time, because the `debian:buster` tag is going to be more similar to a "real" install of Debian Buster -- for example, installing and trying to use `man` is going to do the right thing, which can't be said for the slim variant (by design).
