### ISSUE TITLE
Postgres - FATAL: password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by demonLaMagra** [docker-library/docs#1697]
Hi all, 

Having an issue when running the stock image from docker hub with the following command:

`docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres`

trying to connect to the database from the host machine using psql returns the error `FATAL: password authentication failed for user "postgres"`

Any help of this would be awesome

**Comment by wglambert** [comment]
You didn't [forward a port](https://docs.docker.com/config/containers/container-networking/#published-ports) to the host, but you could still connect to the container's IP, however external connections to the container wouldn't be able to do that without a published port.

```console
$ docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres
e2d42be9623e27ec2bb382bbcaebeae180fd36c4c9e81d573ba3c6a916bfa167

$ docker inspect some-postgres | grep -i ipaddress
            "SecondaryIPAddresses": null,
            "IPAddress": "172.17.0.2",
                    "IPAddress": "172.17.0.2",

$ psql -h 172.17.0.2 -U postgres
Password for user postgres: 

psql (11.7, server 12.2 (Debian 12.2-2.pgdg100+1))
WARNING: psql major version 11, server major version 12.
         Some psql features might not work.
Type "help" for help.

postgres=#
```

With a `-p 5432:5432`:
```console
$ docker run --name some-postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres
7dbed173973ba6ce38d5525c0358103dca960591ce925d2d487e4f1e553f1709

$ psql -h 127.0.0.1 -U postgres
Password for user postgres: 

psql (11.7, server 12.2 (Debian 12.2-2.pgdg100+1))
WARNING: psql major version 11, server major version 12.
         Some psql features might not work.
Type "help" for help.

postgres=#
```

Also this is the wrong repo for Postgres issues, and in the future questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by demonLaMagra** [comment]
Thank you for your suggestion. I had already tried binding the port and on docker for windows I can see that the port is correctly binded. Following your instructions above still there is still an error.

I post here believing there could be an issue with the image that is being pulled from docker.

**Comment by gustavorps** [comment]
SQLSTATE[08006] [7] connection to server at "postgres" (172.22.0.12), port 5432 failed: FATAL: password authentication failed for user "postgres"

![Screenshot from 2022-03-08 10-57-43](https://user-images.githubusercontent.com/516827/157252339-33292826-5aa3-4b9b-9830-c66a9169d290.png)

```yaml
# docker-compose.yml
version: "3"
services:
  traefik:
    image: "traefik:v2.6"
    command:
      - --accesslog
      - --api.insecure
      - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.exposedByDefault=false
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  postgres:
    image: postgres
    hostname: postgres

  adminer:
    image: adminer
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.rule=Host(`adminer.localhost`)
      - traefik.http.routers.adminer.entrypoints=web
```

**Comment by wglambert** [comment]
Your postgres image could use some environment variables for configuration https://github.com/docker-library/docs/tree/master/postgres#environment-variables

For further help you could try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
