### ISSUE TITLE
Include python drivers

### ISSUE THREAD

**Issue by mishawakerman** [docker-library/docs#1771]
I recently went through the process of upgrading my local development container from 2.3.6 → 2.4.0 and had to rebuild some indexes. Without having the python drivers (or python!) in the docker container, I had to install them on my host machine to run `rethinkdb index-rebuild`. It would be great if this could all be done within the container.

**Comment by wglambert** [comment]
You're looking for https://github.com/rethinkdb/rethinkdb-dockerfiles/issues
https://hub.docker.com/_/rethinkdb

They also have a previous issue on including Python drivers https://github.com/rethinkdb/rethinkdb-dockerfiles/issues/6

But I'm going to close since this isn't an image we ([The Docker-Library](https://github.com/docker-library/)) maintain and this is in the `docs` repo
