### ISSUE TITLE
Composer could not find a composer.json file in /app

### ISSUE THREAD

**Issue by yveshema** [docker-library/docs#1800]
I am trying to follow the official guide to install dependencies for my Laravel project. When I run this command:
```
$ docker run --rm --interactive --tty \
  --volume $PWD:/app \
  composer install
```
it throws the following error:
Composer could not find a composer.json file in /app
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

I came here looking for answers and saw that the issue appears to be a common one, but it appears a solution is yet to be found.
I am running this on a Fedora machine and docker version:  19.03.11
I am hoping someone had the same issue and maybe found an workaround.

**Comment by wglambert** [comment]
Composer isn't in the `php` image, there was a discussion on that here https://github.com/docker-library/php/issues/344

There were also some examples in there for installing composer https://github.com/docker-library/php/issues/344#issuecomment-264930244 

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by yveshema** [comment]
After a lot of googling, I was able to solve the issue. It turns out it was selinux related. [This stackoverflow thread] (https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker) provides a comprehensive explanation. In a nutshell, the contents of the mounted folder need to be re-labelled properly (notice the 'z' flag) to enable read access to the files, like so:
```
$ docker run --rm --interactive --tty \
  --volume $PWD:/app:z \
  composer install
```
For clarity, I was actually not using the php image. I was using the [official Composer image](https://hub.docker.com/_/composer) to generate the vendor files which I relied on for building a custom php image.

**Comment by wglambert** [comment]
Cool glad you got it figured out. For the Composer image we don't maintain that ourselves, their repo is over at https://github.com/composer/docker/issues

>https://hub.docker.com/_/composer
>Maintained by: [Rob Bast](https://github.com/alcohol), with [contributions](https://github.com/composer/docker/graphs/contributors) from the community.
Where to file issues: https://github.com/composer/docker/issues

Going to close since this is resolved
