### ISSUE TITLE
Tag 7.4-fpm-buster exiting with code 70

### ISSUE THREAD

**Issue by jefersonralmeida** [docker-library/docs#1836]
I had a working environment using `7.4-fpm-buster`, but I had to rebuild it today, and it stopped to work. 

When I run the `docker-compose up api` (api is the name of my service), it just logs "Exitted with code 70". No additional logs are provided.

Docker version 19.03.2, build 6a30dfc

I tried to downgrade to 7.3, and it worked. Still didn't have time to investigate it in deep. If I found something I'll drop here.

**Comment by wglambert** [comment]
Maybe it's a configuration issue?

What's the docker-compose.yml have in it?

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by jsawicki-internetcompany** [comment]
Are you on Windows? I had a similar problem. 
I solved it by re-adjusting my WSL Integration in Docker Desktop.
