### ISSUE TITLE
How to restart postgresql in container

### ISSUE THREAD

**Issue by just1689** [docker-library/docs#1837]
Hi there

A few of us were wondering how to restart Postgres in the container?

We tried `systemctl`, `service` restart etc.

Kind regards 
Justin

**Comment by wglambert** [comment]
There isn't an init system in the image, Postgres occupies PID 1 so there isn't any "process supervisor" controlling it in the container. If PID 1 tries to restart it first has to exit which causes the container to exit. So you'd need to restart the container itself but then any unpersisted ephemeral changes done to the container aren't saved

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by just1689** [comment]
Ooh thank you. That's a fantastic explanation. 

The reason I'm asking is because we're trying to figure out (on Stackoverflow) how to upgrade a postgres database where Pg is running in the container.

The person who asked the question upped the tag for the `image:` bit in the deployment yaml. However that doesn't migrate the data. For that you need to run a few commands.

I'm curious if this has been documented. I feel like it is a legitimate concern / scenario. If you could point me to docs or suggest something it could go in the stackoverflow question and help others in the future.

Apologies if this is super obvious / already documented clearly and I have managed to miss it completely.

**Comment by tianon** [comment]
Ah, it's definitely not super obvious, and it's actually kind of complicated to get it right; see https://github.com/docker-library/postgres/issues/37 for a *lot* of discussion around that. :sweat_smile:

**Comment by just1689** [comment]
Appreciate it!
