### ISSUE TITLE
how can I add --insecure-registry 

### ISSUE THREAD

**Issue by huatan** [docker-library/docs#1867]
docker run --name did -d --privileged \
--network test-net --network-alias docker \
-e DOCKER_TLS_CERTDIR=/certs -e INSECURE_REGISTRY='192.168.64.3:5050' \
-v did-certs-ca:/certs/ca \
-v did-certs-client:/certs/client \
docker:20.10.2-dind

when i use self-sign cert repository harbor 
![image](https://user-images.githubusercontent.com/60465310/107058091-20431f00-680f-11eb-8700-7f56bdc51849.png)

**Comment by wglambert** [comment]
You can either use `--inescure-registry` 
or add a `daemon.json` at `/etc/docker/daemon.json` https://github.com/docker-library/docker/issues/131

With a `daemon.json` like:
```yaml
{
  "insecure-registries" : ["myregistrydomain.com:5000"]
}
```
https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
