### ISSUE TITLE
unclear credentials for external folders

### ISSUE THREAD

**Issue by MopcSolutions** [docker-library/docs#1874]
It's not clear, which user must be granted rights to access the external folder

**Comment by tianon** [comment]
This sounds like it's probably a usability question?  It might depend on which image you're using too.  I'd suggest trying a dedicated support forum, such as [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by yosifkit** [comment]
Many images, like `mysql` have an "arbitrary user" [section](https://github.com/docker-library/docs/tree/786fbbf92e0503c654574510d7b46cae53aea8b7/mysql#running-as-an-arbitrary-user), so you can run the container as whatever user id you need to (usually except root).

**Comment by wglambert** [comment]
Going to close since there isn't an image in particular that I can think of that has this kind of ambiguity. For any particular image where you might encounter this though you could run an `echo $UID` or check the running processes in the container determine what user/UID you might need, outside of looking through its docs page.
