### ISSUE TITLE
Build a docker image with bashbrew

### ISSUE THREAD

**Issue by tretos53** [docker-library/docs#1923]
Hi,

Is there a simple guide of how to edit `https://github.com/docker-library/docker/blob/master/20.10/Dockerfile` and build a docker image based on official docker:latest image?

For example:

```
$ git clone https://github.com/docker-library/docker.git
$ edit Dockerfile
$ bashbrew build docker:mychanges1
```

Or this is not as simple?

At the moment I'm doing below.

```
$ docker run -it docker:latest sh
$ apk add <some packages and other config I need>
```

`docker commit -p -a "author_here" -m "your_message" <imageid> name_of_new_image`

Sorry for asking maybe stupid question, just trying to understand.

**Comment by wglambert** [comment]
Probably the simplest thing for what you're looking for is:
```dockerfile
FROM docker
RUN apk add . . .
```

In the future questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by tretos53** [comment]
Awesome, thank you.
