### ISSUE TITLE
Can't change DNS servers

### ISSUE THREAD

**Issue by davetayl** [docker-library/docs#2013]
What is the best method for setting the DNS servers using podman, currently on the centos:7 image dns is showing up as 169.254.169.254

**Comment by wglambert** [comment]
Here's a couple pages that might help
https://podman.io/getting-started/network#using-dns-in-container-networks
https://docs.docker.com/config/containers/container-networking/#dns-services

But I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
