### ISSUE TITLE
docker-php-ext-install gd  error: Package requirements (zlib) were not met:

### ISSUE THREAD

**Issue by Ctlynl** [docker-library/docs#2083]
在docker 容器里面执行 报错 docker-php-ext-install gd 
![image](https://user-images.githubusercontent.com/38125573/142572364-04367f71-b3a3-4f08-aeb3-63e5b73f899f.png)

**Comment by wglambert** [comment]
If you're using the Debian variant then you'll want the package `zlib1g-dev`, or if you're using Alpine `zlib-dev`

Questions like these would be better asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by Ctlynl** [comment]
OK, thank you very much
