### ISSUE TITLE
conventional env vars

### ISSUE THREAD

**Issue by ReinsBrain** [docker-library/docs#2242]
Just curious why the change in conventional env vars: https://www.postgresql.org/docs/current/libpq-envars.html ... can i still use the postgresql env vars?

**Comment by yosifkit** [comment]
The docker-specific variables were chosen so that they wouldn't possibly overlap with those environment variables.

So anything that can be used by the `postgres` server or client binaries will be used by them. We account for many of them in the startup script (like `PGDATA` and `PGPORT`), but it is possible that some could cause the initial database creation steps of the [entrypoint script](https://github.com/docker-library/postgres/blob/39c3dc7046f5f7909179a51e25f2a61158781d57/docker-entrypoint.sh) to fail.
