### ISSUE TITLE
I mount `/etc/caddy/Caddyfile` wrong，`/etc/caddy/Caddyfile` is a text file and not a folder.

### ISSUE THREAD

**Issue by Astro-Lee** [docker-library/docs#2284]
https://github.com/docker-library/docs/blob/d6062c648b0ef6ec221c96b10c661ba301e44606/caddy/README.md?plain=1#L108-L115
![~KA~6X$UC@CJ3`S1F)BTVN7](https://user-images.githubusercontent.com/61745903/220960924-bbb96100-d4ed-4b90-b254-e1a41dd75f9f.png)

**Comment by yosifkit** [comment]
Did you create the `$PWD/Caddyfile` on your host first? The target, `/etc/caddy/Caddyfile`, already exists in the container as a file, so you need to create your local one first. If the source, `$PWD/Caddyfile`, doesn't exist, then Docker will just assume you meant a directory and create it; then it fails because it can't mount a directory onto a file.

**Comment by tianon** [comment]
In the future, these sorts of questions/requests would be more appropriately posted to a dedicated support forum, such as [the Docker Community Slack](https://dockr.ly/comm-slack), [Server Fault](https://serverfault.com/help/on-topic), [Unix & Linux](https://unix.stackexchange.com/help/on-topic), or [Stack Overflow](https://stackoverflow.com/help/on-topic).
