### ISSUE TITLE
What means "rc" (lower case) in image tag?

### ISSUE THREAD

**Issue by Arkemlar** [docker-library/docs#2349]
There are many images with `rc` part in name. And [docs](https://github.com/docker-library/docs/blob/master/php/README.md#supported-tags-and-respective-dockerfile-links) says nothing about that.
<img width="1060" alt="изображение" src="https://github.com/docker-library/docs/assets/19671202/da5172c2-bce9-4285-9dab-a7288845c85e">

I suppose it is not same as RC1 (release candidate) because it looks different.
I think there should be any description in docs about that to avoid users getting stuck, like me for example.

**Comment by tianon** [comment]
Yeah, this could definitely use some better docs -- we often (across the program) use `rc` as a generic alias for "pre-release" so that users can pin to the latest pre-release of the given image.

Probably good to include as part of https://github.com/docker-library/official-images/issues/6282 :disappointed:
