### ISSUE TITLE
Clarify node:slim recommendation.

### ISSUE THREAD

**Issue by luebken** [docker-library/docs#299]
(This issue originated here: https://github.com/joyent/docker-node/issues/26)

The node [readme](https://github.com/docker-library/docs/blob/master/node/README.md#nodeslim) notes about the slim package:

> node:slim
> This image does not contain the common packages contained in the default tag and only contains the minimal packages needed to run node. Unless you are working in an environment where only the node image will be deployed and you have space constraints, we highly recommend using the default image of this repository.

But when looking at the [Dockerfile 0.10 slim](https://github.com/joyent/docker-node/blob/3e0d2b62fa8524e05ef512564613863ee7f13255/0.10/slim/Dockerfile) it seems that it is suitable for runtime. As noted here: 

> If your app doesn't need to compile any modules or external dependencies than it should be fine.

https://github.com/joyent/docker-node/issues/26#issuecomment-117184917

So the question is wether and how the description for node:slim could be reworded.

**Comment by tianon** [comment]
I'm definitely +1 on rewording the slim docs (https://github.com/docker-library/docs/blob/046ddc6f448df2168f6aefda2de9c93662e46e1e/.template-helpers/variant-slim.md) to be more clear.

The intention of the existing docs was to point out that if you're not sure what you're doing, you should use the default tag.  If you know what you're doing, the slim tag is definitely the way to go, but there's going to be a lot more manual labor involved with using it, on average.

**Comment by luebken** [comment]
TIL that the `slim` description is is generalised and used in different repos like ruby, python, nodejs

Is there a consensus what `slim` actually means? From what I read `slim` means:
* smaller than the default
* the way to go if you know what to do. (just because of size? other reasons?)
* might require more manual labor

**Comment by yosifkit** [comment]
That sounds about right. The simple way to describe slim is to describe that the not-slim version has lots of default libraries (usually `FROM buildpack-deps`) so that most projects can just run without needing to worry about system packages (ie, `npm install X` will work 95% of the time).  So to save space, slim versions have just enough to run language X. `npm/bundle/pip` will probably need some apt packages to even install a module, but anything that is part of the core of the language will work (ie, things that would require recompiling the language).

**Comment by luebken** [comment]
I know this is an old issue. But a small comment why this is closed would be nice.

**Comment by olof-nord** [comment]
Is there any information available as to why this issue was closed?

I came here to find out more about the non-recommendation of `-slim` as well, this was the first information I found.

**Comment by tianon** [comment]
It was closed because it's lacking a concrete proposal (and the OP was a request for clarification, which was provided) -- the current description for slim variants is generic, and if the `node` image maintainers want something more specific that should probably come in the form of a PR (adding a `node/variant-slim.md` file).

If the question is instead whether `node:slim` is recommended for use or not, I'm afraid https://github.com/nodejs/docker-node or a dedicated support forum, such as [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) is going to be a better / more appropriate place to have that discussion.

**Comment by olof-nord** [comment]
Many thanks for your answer and for the information provided @tianon!
