### ISSUE TITLE
Sentry background jobs instruction

### ISSUE THREAD

**Issue by sivakumar-kailasam** [docker-library/docs#311]
I ran the following commands to setup sentry,

- `docker run -d --name log-analyser-redis redis`
- `docker run -d --name log-analyser-postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=sentry postgres`
- `docker run -d -p 9090:9000 -v /home/siva/log-analyser/ --name log-analyser-sentry --link log-analyser-redis:redis --link log-analyser-postgres:postgres sentry`
- `docker run -it --rm --link log-analyser-postgres:postgres --link log-analyser-redis:redis sentry sentry upgrade`
- `docker run -d --name log-analyser-celery-beat --link log-analyser-redis:redis -e CELERY_BROKER_URL=redis://redis celery celery beat`
- `docker run -d --name log-analyser-celery-worker1 --link log-analyser-redis:redis -e CELERY_BROKER_URL=redis://redis celery`

After logging in, I see this message,

`Background workers haven't checked in recently. This can mean an issue with your configuration or a serious backlog in tasks.`

After this I had to run `sentry celery worker -B &` inside the container to get it to work. This is my first time setting up sentry so there might be a better way to achieve this, but I felt this should've been a part of the docs.

**Comment by yosifkit** [comment]
Your backgrounded task (`sentry celery worker -B &`) is just another celery worker and celery beat; and could break since there is not an init process in the container to monitor secondary process (ie not really the "docker way").  I am not sure if your plain celery containers are even working since that backgrounded task was a new celery worker and would thus make the warning go away.

It seems that there must be more happening with the celery embedded with sentry vs running plain celery with a redis url.  Have you tried running the embedded celery in separate containers?
```console
docker run -d --name log-analyser-celery-beat --link some-redis:redis sentry sentry celery beat
docker run -d --name log-analyser-celery-worker1 --link some-redis:redis sentry sentry celery worker
```

**Comment by aheuermann** [comment]
The worker seems to also need postgres and the `CELERY_BROKER_URL` env variable. I got it working using the following.
```console
docker run -d --name celery-beat --link redis:redis --link postgres:postgres -e CELERY_BROKER_URL=redis://redis sentry sentry celery beat
docker run -d --name celery-worker1 --link redis:redis --link postgres:postgres -e CELERY_BROKER_URL=redis://redis sentry sentry celery worker
```

**Comment by yosifkit** [comment]
@aheuermann, is there not a way to run plain celery workers (ie the `celery` image) or do they have to be celery that is included with sentry?  What extra configuration is being done to them by sentry?

Also, you shouldn't need `CELERY_BROKER_URL` when using the embedded celery since it is setup in [docker-links.conf.py](https://github.com/docker-library/sentry/blob/8852797a684bd16756397729ac02bd8f11fafe20/docker-links.conf.py#L111).

**Comment by sivakumar-kailasam** [comment]
@yosifkit & @aheuermann both suggestions didn't work.

**Comment by aheuermann** [comment]
@yosifkit I don't know much about celery (or the internals of sentry for that matter). I'm guessing it needs the sentry code packaged with it though as that is where the [tasks are defined](https://github.com/getsentry/sentry/blob/master/src/sentry/tasks/store.py).  Also, I found some [celery config here](https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L351).

**Comment by mattrobenolt** [comment]
I'm going to be making this easier soon. :) So hang in there while we take over.

**Comment by mattrobenolt** [comment]
If this is still an issue, reopen under https://github.com/getsentry/docker-sentry/issues

/cc @yosifkit can you close this? :)
