### ISSUE TITLE
Nginx documentation incorrect about daemon off directive

### ISSUE THREAD

**Issue by ustun** [docker-library/docs#316]
The latest version of this dockerfile has an entry point that already adds daemon off, so the following note in https://github.com/docker-library/docs/blob/master/nginx/content.md is wrong:

`
Be sure to include daemon off; in your custom configuration to ensure that Nginx stays in the foreground so that Docker can track the process properly (otherwise your container will stop immediately after starting)!
`

Actually, if you include `daemon off`, nginx will not start because of duplicate directive.

**Comment by md5** [comment]
The docs are fine since that section is talking about replacing `/etc/nginx/nginx.conf` entirely, not adding additional configurations under `/etc/nginx/conf.d`. If a user were to replace the entire stock configuration without having `daemon off;` somewhere in their config, then `nginx` would daemonize and the container would exit.

**Comment by md5** [comment]
Argh... I just reread your comment about the fact that the entrypoint is adding `daemon off;`. Sorry!

**Comment by ustun** [comment]
Yes, please see

https://github.com/nginxinc/docker-nginx/blob/f4f58b1c4b433b0f82687a326d9c79d216c41de9/Dockerfile#L22

**Comment by joshperry** [comment]
FYI, just wasted an hour on this simple docu edit.

**Comment by yosifkit** [comment]
Closing in favor of https://github.com/nginxinc/docker-nginx/issues/41.
