### ISSUE TITLE
MongoDB - How to get/set password?

### ISSUE THREAD

**Issue by JulianKingman** [docker-library/docs#369]
I'm looking to connect to the db remotely with robomongo, but I need to know the password for that, is there an environmental variable I can set for the PW or can I find it somewhere? I expected it to appear in the logs, but it didn't show up for me...

**Comment by dmitrym0** [comment]
You can set the root password with the `MYSQL_ROOT_PASSWORD` environment variable, see the readme on the main repo page.

**Comment by JulianKingman** [comment]
Whoops, this is for mongo, I didn't realize I was opening an issue for all the official docker repos.

**Comment by yosifkit** [comment]
This issue would be slightly better over in https://github.com/docker-library/mongo, but it works here too.  There is no password by default on a mongo instance, there was some talk in https://github.com/docker-library/mongo/pull/48 about adding documentation on setting up `--auth`.

The problem that exists is that setting it requires that you connect through localhost to set up the initial admin, which can only be done via a process within the same network namespace via `docker exec` or `--net`.  We have thought about have similar environment variables like the sql databases, but that would require starting mongodb in a separate process, creating the user, killing mongodb, and then starting mongodb again as the main process of the container.

**Comment by JulianKingman** [comment]
Huh... could it be set up with a ````--link```` or set up a default user/password on creation (from within the container)?

**Comment by yosifkit** [comment]
The current way to turn on auth to mongodb is to just run it with `docker run -d --name my-mongo -v /my/local/:/data mongo --auth`.  `--link` wouldn't work to access the mongo shell since that would still be a non-localhost network connection.  It would need to be done through within the container through `docker exec` or another container within the same network namespace with `--net=my-mongo`.

We have debated adding support to create an initial user with an environment variable like MySQL/Postgres/MariaDB/Percona, but have, so far, decided that the added complexity is not worth it.
