### ISSUE TITLE
tag latest

### ISSUE THREAD

**Issue by JurrianFahner** [docker-library/docs#382]
When will the tag latest on docker hub refer to more recent versions of ubuntu, instead of refering to 14.04? Or will it always refering to the latest LTS release?

**Comment by tianon** [comment]
Arg, I swear we'd added this to the image description, but it's nowhere to be found.  `latest` is a misnomer (it should've been `default`) -- since it's what's used when the user doesn't specify a tag explicitly, we try to keep it pointing at the tag that's "recommended for general use".  In Ubuntu's case, that's the "latest LTS release", which is why it currently points to 14.04, but will switch to 16.04 later this year. :+1:

(This really ought to be documented in https://github.com/docker-library/docs/blob/master/ubuntu/content.md :disappointed:)
