### ISSUE TITLE
Modification of the "Supported Versions" text

### ISSUE THREAD

**Issue by Djelibeybi** [docker-library/docs#404]
We need to be able to change the text added to the documentation under the "Supported Versions" heading. This is so that we can direct our customers to the appropriate support services based on whether they have a paid subscription or not.

Also, we need to be able to specify the currently supported distribution version of Docker, which may differ from the upstream release.

**Comment by Djelibeybi** [comment]
Note that changing the `CONTENT.md` isn't suitable, as we'd still be left with a confusing "Supported Versions" block.

**Comment by tianon** [comment]
Hmm, interesting requirements -- for the second half of that, you _should_ be able to add `oraclelinux/docker-versions.md` (which will override the contents of `.template-helpers/docker-versions.md`).

The first bit is a little more challenging, since I don't think the templating scripts as-is have a good mechanism for supporting that sort of customization.  Do you think you could whip up an example of what you'd like the output to be so we can evaluate better how best to implement/support it?

**Comment by Djelibeybi** [comment]
Resolved via #464 which is sufficient for our purposes. Thanks for the tip to create `docker-versions.md`.

**Comment by tianon** [comment]
Nice, glad that did it! :smile:
