### ISSUE TITLE
Add OpenEDX

### ISSUE THREAD

**Issue by arkhan** [docker-library/docs#420]
It's posible to add instrucctions to install OpenEDX whith docker...?
[OpenEDX](https://github.com/edx/configuration/tree/master/docker)

**Comment by yosifkit** [comment]
Since OpenEDX is not an part of the [official images](https://docs.docker.com/docker-hub/official_repos/), the documentation would not be here. I would ask over in their repo for directions on running it.  It does look like they have a [docker-compose.yml file](https://github.com/edx/configuration/blob/master/docker/compose/edx/docker-compose.yml), so that looks like a place to start
