### ISSUE TITLE
Problem to launch simple script

### ISSUE THREAD

**Issue by pollardino** [docker-library/docs#431]
Hi guys, i'm triying to launch a simple node script, as you comment, I ran this line:
`docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app node:5.3.0-wheezy node script.js`
but, it seems not work.

My "simlpe scrip (script.js)" contain:
```
var http = require('http'),
	fs = require('fs');

http.createServer(function(req, res) {

	fs.readFile('./index.html', function(err, html) {

		var html_string = html.toString();
		// Expresion regular que busca donde haya: {}
		var variables = html_string.match(/[^\{\}]+(?=\})/g);

		var nombre = 'Cristian Buffa';
		
		for (var i = variables.length - 1; i >= 0; i--) {
			var value = eval(variables[i]);

			html_string = html_string.replace("{"+variables[i]+"}", value);
		};

		res.writeHead(200, {'ContentType': 'text/html'})
		res.write(html_string);
		res.end();
	});
}).listen(8080);
```

can someone help me?

**Comment by Moghedrin** [comment]
Without more information on what the problem is, it's hard to say, but my guess is that you're trying to look at "http://localhost:8080" to test it, but you aren't mapping the host port to the container port with something like `-p 8080:8080`, so it IS working, but just not doing what you expect because of how networking with docker works.

**Comment by pollardino** [comment]
You' re right... Y forgot the port. Awesome. Thanks
