### ISSUE TITLE
Setting up SMTP Mail Settings

### ISSUE THREAD

**Issue by marpe** [docker-library/docs#516]
Hi,

I don't understand how I'm supposed to configure the mail settings for Sentry. Looking at the environment variables that are set I can see that EMAIL_BACKEND is set to 'django.core.mail.backends.**dummy**.EmailBackend'. I suppose this isn't correct, but setting this environment variable isn't documented in the readme for the image.

https://github.com/docker-library/docs/tree/master/sentry

**Comment by mattrobenolt** [comment]
Hey, I just noticed this. These issues should be opened over here: https://github.com/getsentry/docker-sentry so someone from our team sees them.

You want to set `SENTRY_EMAIL_HOST` and friends, as you can see here: https://github.com/getsentry/docker-sentry/blob/master/8.3/sentry.conf.py#L222 there's no need to set `EMAIL_BACKEND` directly, but if no email config is specified, we'll fall back to `dummy`.

I also can't close this issue since I'm not an owner of this repository. :( /cc @yosifkit

**Comment by marpe** [comment]
Thanks! :)
