### ISSUE TITLE
can't find third party libraries

### ISSUE THREAD

**Issue by carlskii** [docker-library/docs#519]
Hi,

I cant get my go application to compile. I'm running this:

`docker run --rm -v "$PWD":/usr/src/myapp -v "$GOPATH":/go -w /usr/src/myapp golang:1.6 go build -v`

from within the directory that contains my go application that has a dependency on a third party library but it throws the following error:

```
event_monitor.go:5:2: cannot find package "github.com/fsouza/go-dockerclient" in any of:
        /usr/src/go/src/github.com/fsouza/go-dockerclient (from $GOROOT)
        /go/src/github.com/fsouza/go-dockerclient (from $GOPATH)
```

Obviously its not finding the dependancies but I'm not sure what I'm doing wrong. My directory structure looks like this:

```
em (point from where i'm running docker run) 
    event_monitor.go (main go app)
    src
        github.com
            fsouza
                go-dockerclient
```

**Comment by tianon** [comment]
Sorry for the long tail on responding to this.  This is actually working as designed -- `go build` will not automatically fetch dependencies, and requires that you use `go get` (or some other means) to collect them yourself.  What I'd recommend is using a `Dockerfile` so that you can benefit from cache, something like this:
```dockerfile
FROM golang:1.6
RUN go get -v github.com/fsouza/go-dockerclient
WORKDIR /go/src/em
COPY . .
RUN go install -v ./...
CMD ["em"]
```

You could also work around the problem by adjusting your `docker run` line to replace `go build` with something like `sh -c 'go get -v && go build -v'`, but then you're going to be re-downloading the source every time you run.  I _think_ with the new vendoring support, you could also rename your local `src` directory to `vendor` and that might work, but it's still iffy (given `GOPATH` constraints). :+1:
