### ISSUE TITLE
SENTRY_SERVER_EMAIL

### ISSUE THREAD

**Issue by SUNNYANDPJ** [docker-library/docs#543]
sorry~i really donnot how to set this params~~

**Comment by mattrobenolt** [comment]
Hey @SUNNYANDPJ You should be able to specify this with the environment variable `SENTRY_SERVER_EMAIL`. Starting with 8.3 though, it's not necessary to specify, and you'll be prompted during the installation wizard for the value.

See: https://github.com/getsentry/docker-sentry/blob/master/8.3/sentry.conf.py#L241

Also, in the future, please don't open issues here since nobody from Sentry team seems them. Please open at https://github.com/getsentry/docker-sentry/issues.

I also can't close this issue here since I'm not a contributor on this repository. /cc @yosifkit
