### ISSUE TITLE
[rabbitmq] How to make it externally accessible?

### ISSUE THREAD

**Issue by bluepuma77** [docker-library/docs#633]
1. Can you please provide information on how to expose RabbitMQ outside of the Docker container?Deprecated [tutum/rabbitmq](https://github.com/tutumcloud/rabbitmq) had this mentioned on their first page with `-p 5672:5672 -p 15672:15672`.
2. Furthermore it would be great to show how to build a cluster on multiple servers. Your first technical point is the `Erlang Cookie` for building a cluster, but you then only use a single server via --link.
3. Finally, the `Management Plugin` includes full RabbitMQ? It's not really clear to me from the document. Or is it just the Plugin and it needs to be linked to a pure RabbitMQ container?

**Comment by Moghedrin** [comment]
1) There's a few reasons we don't like adding examples with port forwarding in examples these days. Our general stance is that exposing ports is a function of docker, rather than the images, and the documentation for the images is supposed to be specific to the image (what environment variables it expects, what arguments, etc).

2) This is outside the scope of the image use and gets more into RabbitMQ configuration and orchestration.

3) To quote the documentation:
>There is a second set of tags provided with the management plugin installed and enabled by default, which is available on the standard management port of 15672, with the default username and password of `guest` / `guest`
This is a variant of the RabbitMQ image with the management plugin installed. It should be running RabbitMQ with the plugin enabled.
