### ISSUE TITLE
The README should mention bashbrew

### ISSUE THREAD

**Issue by Saser** [docker-library/docs#643]
The README makes no mention of `bashbrew`, but it seems that it is needed to use `update.sh` without getting any errors. I found this when I did the following commands:

```console
$ git clone git@github.com:docker-library/docs.git
$ cd docs
$ vim postgres/content.md # Made some small changes here
$ ./update.sh postgres
  TAGS => generate-dockerfile-links-partial.sh
.template-helpers/generate-dockerfile-links-partial.sh: line 11: bashbrew: command not found
```

I can see that the `postgres/README.md` file has been updated accordingly, but getting a `command not found` error initially made me think that the `update.sh` script had failed. I can see that the `update-tag-details.sh` script contains the following lines:

```bash
# going for "bashbrew: command not found"
bashbrew --help > /dev/null
```

So apparently, this is intentional. However, I think that the README should have a mention of `bashbrew` -- perhaps how to install it? It seems to be available in [`docker-library/official-images`](https://github.com/docker-library/official-images) -- or clarify that getting `bashbrew: command not found` might not necessarily be an error.

**Comment by yosifkit** [comment]
:open_mouth: I guess we hadn't thought of that.  I think most contributors have been ignoring `update.sh` since we don't accept PRs with changes to a repo's readme file and we have it on a periodic jenkins job anyway.  It does make sense to be able to run it locally so that you can see what the changes would be.

Perhaps a docs note that you need the [`basbrew`](https://github.com/docker-library/official-images/tree/master/bashbrew) executable (or a symlink to `bashbrew.sh`) in your `PATH` if you want to run the update script or maybe make the script skip the parts that need `bashbrew` when it does not exist and print a warning that the those sections will not be accurate.

**Comment by pierreozoux** [comment]
Got bitten right now.

Maybe we should the update script should call a docker image :) This way, we don't care about dependencies. And people contributing here have docker installed :)
