### ISSUE TITLE
PHP: weird volume mounting issue

### ISSUE THREAD

**Issue by dmitrybelyakov** [docker-library/docs#650]
Hi!

For some reason I'm getting unexpected results with *-`fpm` images when mounting a directory as `/var/www`. I can mount to other locations normally though, for example `/var/www2` works alright.

```
cd ~
mkdir docker_test

# this works
docker run -it -v $(PWD)/docker_test:/var/www php:5.6 bash

#fpm image does not
docker run -it -v $(PWD)/docker_test:/var/www php:5.6-fpm bash
```

I tried several versions and its always the same - fpm images give me this error:

```
docker: Error response from daemon: oci runtime error: no such file or directory.
```

I'm on docker for mac. Latest stable.

**Comment by yosifkit** [comment]
That would be because the fpm image sets a [workdir](https://github.com/docker-library/php/blob/2cc40ce1de4206a9bc55e38331937b4bd7d58700/5.6/fpm/Dockerfile#L91); if you are mounting a directory above that and thus hiding the `html` directory it will fail to start.  The same would happen on the `apache` variants.

Two solutions:
 - set your own workdir: `docker run -it -w /var/www -v $(PWD)/docker_test:/var/www php:5.6-fpm bash`
 - make sure html exists on your host `mkdir $(PWD)/docker_test/html`

**Comment by dmitrybelyakov** [comment]
Oh, I see. Thank you very much, @yosifkit :)
