### ISSUE TITLE
Redis: Add documentation for docker-compose

### ISSUE THREAD

**Issue by jimzucker** [docker-library/docs#684]
Note: I will propose a pull request.

It would be useful to enhance the documentation on the dockerhub image to give instructions for docker compose.

i.e.. adding a config file, right now the image documentation explains how to create a new docker image but using the docker-compose is very convient to setup an environment.  see http://stackoverflow.com/questions/30547274/docker-compose-anyway-to-specify-a-redis-conf-file

From the Stack Overflow, example on how to set a config file:

command: redis-server /usr/local/etc/redis/redis.conf
volumes:
 - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

**Comment by yosifkit** [comment]
In that [same section](https://github.com/docker-library/docs/blob/a74055f6db43a28b8e04fe16b24b5a547440d4db/redis/content.md#additionally-if-you-want-to-use-your-own-redisconf-) of the readme there is the example of using a config file without building an image:

> Alternatively, you can specify something along the same lines with docker run options.
```console
$ docker run -v /myredis/conf/redis.conf:/usr/local/etc/redis/redis.conf --name myredis redis redis-server /usr/local/etc/redis/redis.conf
```

Any of these `docker run` flags are directly correlated to parts of the docker-compose.yml, so I feel like most users of compose should know how to switch between the two.

With the current [entrypoint script](https://github.com/docker-library/redis/blob/ec0cb4dab9ed6e60cc0863cd3477a013fb4c0596/3.2/docker-entrypoint.sh) it is also possible to skip the `redis-server` in the `command`, so that our current example becomes:
```console
docker run -v /myredis/conf/redis.conf:/usr/local/etc/redis/redis.conf --name myredis redis  /usr/local/etc/redis/redis.conf
```

On a side note, there is no default config file and it mostly* does not actually matter where you put the config file in the image since you have to pass it to redis anyway.  Also, "Since Redis 2.6 it is possible to also pass Redis configuration parameters using the command line directly" ([redis.io](http://redis.io/topics/config)).

<sub>\* permissions of the containing folders in the image could play a factor</sub>

**Comment by yosifkit** [comment]
This looks like it was solved, closing. Feel free to comment if you feel this was closed in error.

**Comment by mheiber** [comment]
@yosifkit you wrote:

> Any of these docker run flags are directly correlated to parts of the docker-compose.yml, so I feel like most users of compose should know how to switch between the two.

I have no idea and am very confused. How do I tell Redis to use my conf file?

I tried this, and the container doesn't even run:
        command:  redis-server redis /usr/local/etc/redis/redis.conf

**Comment by tianon** [comment]
@mheiber drop the intermediate `redis` there:
```yaml
command: redis-server /usr/local/etc/redis/redis.conf
```

**Comment by mheiber** [comment]
Thanks!
