### ISSUE TITLE
ova compiling

### ISSUE THREAD

**Issue by sosher** [docker-library/docs#696]
Hi , having issues with compiling for ova 
after installing vddk 6.0.2 & ovftool
moving to the right ?? location /usr/lib/vmware & /usr/include/vmware

I still run into issues running make cloud-image IMG_NAME=ova. I think I narrowed it down to vix-disklib-util.
the errors are
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lfuse

any Ideas ?

BTW
isnt there a better platform to get support .. I feel awkward posing these kinda of issues here.

Thanks.

**Comment by yosifkit** [comment]
My guess is that you are trying to build a root disk image for `photon`? My guess is based on their [docs](https://github.com/vmware/photon/blob/d0453118285e23aeac3e3eca4af7deba2229bc1e/docs/cloud-images.md#how-to-build-cloud-images); maybe report an issue over there?

If you have issues with the Docker image for photon, that should probably be reported on [their](https://github.com/vmware/photon-docker-image/issues) repo, since this repo is for the documentation of Docker Official Images and many of the individual image maintainers do not watch here.

**Comment by sosher** [comment]
lol... I am sorry too many tabs open.. I posted in the wrong git ...
