### ISSUE TITLE
excessive logging

### ISSUE THREAD

**Issue by theresiasnow** [docker-library/docs#762]
Hi,

the wordpress docker image logs a lot to a json file inside /var/lib/docker quickly filling the filesystem.
How can I configure this? Looks like access logs

**Comment by yosifkit** [comment]
With the default `json-file` logging driver in docker, you can specify a `--log-opt max-size` and `--log-opt max-file` to docker so that it will keep the file(s) at reasonable amounts. Or you can use one of the other docker logging drivers: https://docs.docker.com/engine/admin/logging/overview/.

As for telling apache/php to log less, I think that would be changing or overriding the config files in `/etc/apache2/`.

**Comment by theresiasnow** [comment]
Thanks, I did it the docker way
