### ISSUE TITLE
Mongo as Certificate DB

### ISSUE THREAD

**Issue by Pierpaolo1992** [docker-library/docs#829]
Hi, i'm studying WebTRTC Security. This is a p2p architecture, so i'd like that my javascript application, from my first peer, could POST a string to this MongoDB container; from second peer, i'd like he could get all the message(string) stored in MongoDB container (inserted by every first peer). This because the second peer has to check the presence of this message in the DB.
Is this feasable with MongoDB?

Thanks to everyone.

**Comment by yosifkit** [comment]
Access to the MongoDB running in the container would be basically the same as running it on a server, as long as all the peers can access the database, they could set or get messages in a collection there.

I would caution about setting up a database that is directly accessed by an end user application across the internet; usually a web service is placed between the database and application to provide an api with authentication.  Especially since remotely open databases are easy to hijack: https://www.bleepingcomputer.com/news/security/number-of-hijacked-mongodb-databases-is-going-up-as-more-hackers-are-flocking-in/.
