### ISSUE TITLE
[postgres] Instructions to connect to postgres container from host

### ISSUE THREAD

**Issue by mlovic** [docker-library/docs#845]
Under "How to use this image", the docs conveniently feature instructions/commands to connect to postgres from another container using `--link`. It doesn't, however say anything about how to connect from the host. 

This is pretty straightforward, except for the fact that by default `psql` won't find the server if it's not on the local 127.0.0.1 interface (or that's my understanding at least). 

My network/systems experience is limited and it took me a while to figure this out (`psql -h 0.0.0.0 -U postgres` worked for me). This behaviour is also different for other projects like Redis, i.e. `redis-cli` will find the server without specifying the host.

I'm pretty new to docker and maybe this is mostly assumed knowledge, so feel free to ignore, but I'd like to suggest adding it to the image docs. 

If others agree, I'd be happy to submit a PR :). And please let me know if I'm missing anything here, thanks!

**Comment by Moghedrin** [comment]
Dealing with docker networking is largely outside the scope of what we intend to provide as image documentation of the official images: this has more to do with working with understanding docker and networking generally than it does specific images.

As far as running `psql -h 0.0.0.0 -U postgres`, that shouldn't be connecting to your postgres container if you ran the same command as the documented example. Usually, 0.0.0.0 is only used when listening for connections/packets. When trying to connect, it usually will resolve to 127.0.0.1.

You were able to connect because either you have a local postgres instance running on your machine that you were connecting to, you set up portforwarding on the container (the best way to do this), or you told the container to use the host's network namespace.

Setting up portforwarding for the container is the way to go here, and following from the documentation example, you would run your container like so:

```
docker run --name some-postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres
```

Then, you should be able to connect to the container as you would a local instance of postgres.
```
psql -h localhost -U postgres
```
