### ISSUE TITLE
Permission denied serving content

### ISSUE THREAD

**Issue by shukriadams** [docker-library/docs#883]
I'm getting a 403 forbidden / permission denied error on all static content. Right now I'm trying to do a simple hello world. My dockerfile looks like : 
 
    FROM nginx

    COPY content /usr/share/nginx/html

I'm running my container with 

    docker run --name CONTAINER -p 81:80  -dit MY/IMAGE

if I "docker logs CONTAINER" I get 

    2017/04/17 16:04:30 [error] 7#7: *1 open() "/usr/share/nginx/html/index.html" failed (13: Permission 
    denied), client: 172.17.0.1, server: localhost, request: "GET / HTTP/1.0", host: "127.0.0.1:81"

if I add the following line to the end of my docker file
    
    RUN chmod 777 -R /usr/share/nginx/html
    
my static content is served normally, but, it fails for anything nested more than one folder deep, ie, everything in the root and in a folder in the root is served, everything else throws the same permission error. It fails on all kinds of files - JS, images, HTML. For what it's worth, I'm also on Ubuntu 16.04 inside Virtualbox.

Update :

After creating my container, listing out the files in the static content folder "fixes" all permission errors

    docker exec CONTAINER ls -ls -R /usr/share/nginx/html

but makes absolutely no sense.

**Comment by tianon** [comment]
This sounds like it's still a permissions error, but might be interacting with the graph driver in some way (AUFS and overlayfs sometimes have odd behavior when changing the permissions of files in lower layers).

I'd recommend asking for help in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Closing since this isn't really an issue with the docs. :heart:
